config/routes.rb
Habit::Application.routes.draw do

  # things
  post ':user_id/thing/:template_id/create' => 'main#create_thing'
  post ':user_id/thing/:thing_id/destroy' => 'main#destroy_thing'
  post ':user_id/thing/:thing_id/edit' => 'main#edit_thing'

  # templates
  post ':user_id/template/create' => 'main#create_template'
  post ':user_id/template/:template_id/destroy' => 'main#destroy_template'
  post ':user_id/template/:template_id/edit' => 'main#edit_template'

  # misc
  get ':user_id' => 'main#home', :as => :user
  get ':user_id/csv' => 'main#export_csv', :as => :export_csv
  get ':user_id/date/:date' => 'main#home'
  get ':user_id/email' => 'main#email'
  root :to => 'main#create_user'
end

app/views/layouts/application.html.haml
!!! 5
%html
  - cache('head') do 
    %head
      %meta{:charset => "utf-8"}
      %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
      %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
      %title DayScore.net - Reinforce positive habits by keeping score
      %link{:rel => "shortcut icon", :href => "/assets/favicon.ico"}    
      = stylesheet_link_tag "application", :media => "all"
      = csrf_meta_tags   
      = javascript_include_tag "application"   
  %body
    / 
      server time (UTC): #{ Time.now.utc }
      user time: #{ Time.now.utc + @user.time_diff}
      user day: #{ @user.user_today }
    #main{:role => "main"}
      .container  
        %header.jumbotron.subhead
          .row
            .span12
              #alert
            .span7
              %h1
                = link_to 'DayScore', :user
              %p.lead 
                Reinforce positive habits by keeping score. 
                %br
                - link = 'http://dayscore.net' + user_path(@user.rand_str)
                = link_to 'Bookmark this page', link, class: 'bookmark-link'
                and come back tomorrow to update your score.
            .span5
              .extras
                %ul
                  %li
                    %a.toggle-datepicker{href:'#'} Change day
                    %br
                    .datepicker-wrap
                      - default_date = @date ? @date : Date.today 
                      %input.datepicker{'type' =>'text','data-behaviour' => 'datepicker', 'value' => default_date.strftime("%Y/%m/%d")}
                  %li
                    = link_to 'Export data (CSV)', :export_csv
        = yield
        :javascript
          window.user_random_string = "#{@user.rand_str}";
          window.chart_data_hash = eval(#{@date ? @user.chart_data(@date).to_json : @user.chart_data().to_json});
        - if @date
          :javascript
            window.active_date = "#{@date}";

        - cache('footer_and_javascript') do
          %footer.footer
            .row
              .span12
                .pull-right.copyright
                  &copy; 2012 
                  = link_to 'Peter Ellis Jones', 'http://ukoki.com'
          :javascript
             var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-29268598-4']);
            _gaq.push(['_setDomainName', 'dayscore.net']);
            _gaq.push(['_trackPageview']);

            (function() {
              var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
              ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();